-- Loot Wishlist: User-facing strings.
-- Centralised here so wording can be tweaked without hunting through feature
-- files. Format strings use Lua's standard %s / %d placeholders; pass through
-- string.format at the call site.
--
-- Debug and dev-command output stays inline with the code that emits it, being
-- diagnostics rather than copy. So do Const.DIFFICULTY_NAMES: Const.DiffTag
-- matches on their wording to work out a difficulty tag, so they are keys as
-- much as labels and cannot be reworded freely.

LootWishlist = LootWishlist or {}

LootWishlist.Strings = LuckyStrings.New("LootWishlist.Strings", {
    addon = {
        title  = "Lucky's Loot Wishlist",
        short  = "Loot Wishlist",
        prefix = "|cffC9A84CLoot Wishlist|r: ",
        loaded = "Loot Wishlist loaded. Track loot from the Adventure Guide! Use /wishlist for help.",
    },

    minimap = {
        tooltipTitle = "|cffffd100Lucky's Loot Wishlist|r",
        leftClick    = "Left-click: %s",
        ctrlClick    = "Ctrl-click: %s",
        shiftClick   = "Shift-click: %s",
        rightClick   = "Right-click: Open settings",
        middleClick  = "Middle-click: Toggle dev mode",
        drag         = "Drag: Move button",
        actionBoth     = "Wishlist and Loot Browser",
        actionWishlist = "Wishlist only",
        actionBrowser  = "Loot Browser only",
    },

    templates = {
        defaultWhisper = "Hey %looter%. If %item% is tradeable and you don't need it, could I roll on it? Been after that one.",
        defaultParty   = "If %item% can be traded and isn't an upgrade for you, I'd really appreciate it.",
    },

    alerts = {
        dropped            = "Wishlist item dropped:",
        lowerTrack         = "Same item, on a lower track than the %s copy on your wishlist.",
        lowerTrackUnnamed  = "Same item, on a lower track than the copy on your wishlist.",
        rollNow            = "Roll now if needed!",
        unknownItem        = "[unknown]",
        fallbackItem       = "[item]",
        whisper            = "Whisper",
        party              = "Party",
        dismiss            = "Dismiss",
        fallbackWhisper    = "Hi %s, grats! If %s is tradeable, could I please have it? It's on my wishlist.",
        fallbackParty      = "If %s is tradeable, I'd love it (wishlist). Thanks!",
        whisperCommand     = "/w %s %s",
    },

    wishlist = {
        title              = "Loot Wishlist",
        unknownBoss        = "Unknown Boss",
        manuallyAdded      = "Manually Added",
        anySpec            = "|cff8a7e6a{any spec}|r",
        raidTag            = "  |cffff8000[Raid]|r",
        instanceHeading    = "|cffffd100%s|r  (%d)%s",
        bossHeading        = "   |cffc9a84c%s|r  (%d)",
        noItems            = "No items",
        oneItem            = "1 item",
        manyItems          = "%d items",
        clearAll           = "Clear All",
        clearAllConfirm    = "This will remove ALL wishlist items for this character. Are you sure?",
        export             = "Export",
        import             = "Import",
        close              = "Close",
        browseLoot         = "Browse Loot",
        removeFromWishlist = "Remove from wishlist",
        bonusRollTitle     = "Mark as bonus roll target",
        bonusRollLine1     = "Reminds you to spend a Nebulous Voidcore charge",
        bonusRollLine2     = "after a M+ 10+ run or Heroic/Mythic raid boss kill.",
    },

    browser = {
        title             = "Loot Browser",
        trackVeteran      = "Heroic dungeons, Raid Finder raids",
        trackChampion     = "Mythic dungeons, Normal raids",
        trackHero         = "Mythic+ dungeons from +%d, Heroic raids",
        trackMyth         = "Mythic+ vault from +%d, Mythic raids",
        journalNotReady   = "Journal data is not available yet. Try again in a moment.",
        waitingForJournal = "Waiting for the Adventure Guide to close...",
        loading           = "Loading...",
        unknownBoss       = "Unknown Boss",
        noItems           = "No items.",
        noMatches         = "No matches.",
        status            = "|cffe8dcc8%d|r item%s shown%s|cffe8dcc8%d|r on wishlist",
        classLoot         = " loot",
        viewOnly          = "view only, switch back to your class to add",
        noTrackTable      = "journal has no %s table, showing %s",
        entireSeason      = "Entire Season",
        allDungeons       = "All Dungeons",
        allRaids          = "All Raids",
        addToWishlist     = "Add to wishlist",
        removeFromWishlist = "Remove from wishlist",
        veryRare          = "Very Rare",
        bySlot            = "By Slot",
        bySource          = "By Source",
        allSlots          = "All Slots",
        searchPlaceholder = "Search items, bosses, slots...",
    },

    bonusRoll = {
        reminderTitle = "Bonus Roll Reminder",
        charges       = "Charges: %d  (cost %d per roll)",
        available     = "Bonus Roll Available",
        spendOne      = "Spend a charge in |cffffd100%s|r:",
        spendMany     = "Spend %d charges on |cffffd100%s|r:",
        thisDungeon   = "this dungeon",
        thisBoss      = "this boss",
        noneFlagged   = "(no items flagged for bonus roll)",
        testTitle     = "Bonus Roll Reminder (Test)",
        testSubtitle  = "Test popup",
    },

    share = {
        exportTitle       = "Export Wishlist",
        importTitle       = "Import Wishlist",
        notAnExport       = "that string is not a Loot Wishlist export.",
        newerVersion      = "that string was made by a newer version of Loot Wishlist. Please update the addon.",
        noItems           = "that string contains no wishlist items.",
        tooManyItems      = "that string holds more than %d items and cannot be imported.",
        oneItem           = "1 item",
        manyItems         = "%d items",
        imported          = "imported %s, replacing your old wishlist.",
        allAlreadyTracked = "every item in the import was already on your wishlist.",
        addedOneExisting  = "added %s to your wishlist. 1 item from the import was already tracked.",
        addedManyExisting = "added %s to your wishlist. %d items from the import were already tracked.",
        added             = "added %s to your wishlist.",
        nothingToExport   = "your wishlist is empty, nothing to export.",
        importPrompt      = "Import %s: add to this character's wishlist, or replace it?",
        importAdd         = "Add",
        importReplace     = "Replace",
        importCancel      = "Cancel",
        tooManyPopups     = "could not ask how to import, too many popups are on screen. Close them and import again.",
    },

    journal = {
        trackItem      = "Track this item",
        noItemID       = "Loot Wishlist: Could not find item ID for this item",
        bonusRollTitle = "Mark as bonus roll target",
        bonusRollLine1 = "Reminds you to spend a Nebulous Voidcore charge",
        bonusRollLine2 = "after running this dungeon (M+ 10+) or killing",
        bonusRollLine3 = "this raid boss (Heroic / Mythic).",
    },

    vault = {
        title       = "Loot Wishlist",
        matchesLine = "This reward matches an item on your wishlist:",
        onWishlist  = "On your Wishlist:",
    },

    planner = {
        appropriateSpec  = "appropriate spec",
        currentSpec      = "current spec",
        wrongSpecItems   = "Wrong loot spec for wishlist items:",
        switchFor        = "- Switch %s for %s",
        stayFor          = "- Stay %s for %s",
        okAnySpec        = "- OK in any spec: ",
        wrongSpecBosses  = "Wrong loot spec for upcoming bosses:",
        bossSwitchFor    = "- %s: switch %s for %s",
        bossStayFor      = "- %s: stay %s for %s",
        bossOkAnySpec    = "- %s: OK in any spec: %s",
        askGroup         = "Ask group to help with wishlist items:",
        askGroupLine     = "- %s (%s): %s",
    },

    reminders = {
        assistWhisper  = "Hey %s, could you set your loot spec to %s for %s? It's on my wishlist.",
        assistParty    = "%s, could you set loot spec to %s for %s?",
        whisperCommand = "/w %s %s",
    },

    settings = {
        debugMode          = "Debug mode",
        debugModeDesc      = "Prints what the addon is doing to chat. Useful when reporting a problem.",
        minimapButton      = "Minimap button",
        minimapButtonDesc  = "Show the Loot Wishlist button on the minimap. The Minimap group sets what each click opens.",

        whatsNew           = "What's New",
        versionInfo        = "Version info",
        utilsLabel         = "Lucky's Utils",

        groupWishlist      = "Wishlist",
        groupSummary       = "Summary",
        groupAlerts        = "Alerts",
        groupMinimap       = "Minimap",
        groupMessages      = "Messages",

        trackHigher        = "Also track higher difficulties",
        trackHigherDesc    = "Adding a dungeon item on Normal also tracks it on Heroic, Mythic and Mythic+. Turn this off to track only the difficulty you picked.",
        vaultStar          = "Star wishlist items in the Great Vault",
        vaultStarDesc      = "Puts a pulsing star on any Great Vault reward you track. Hover the star to see which wishlist entries it matches.",
        hideWardrobe       = "Hide the Wardrobe model preview",
        hideWardrobeDesc   = "Stops Lucky's Wardrobe showing your character wearing an item when you hover a row in the wishlist or the Loot Browser. The preview still works everywhere else in the game.",

        hideSummary        = "Hide the summary window",
        hideSummaryDesc    = "The summary window is the small note listing what you track, grouped by dungeon and boss. Ticking this keeps it off the screen without changing your wishlist.",
        hideSummaryCombat  = "Hide the summary in combat and Mythic+",
        hideSummaryCombatDesc = "The summary window disappears while you are in combat or inside a Mythic+ run, then comes back when you leave.",
        summaryOpacity     = "Summary opacity when not hovered",
        summaryOpacityDesc = "How solid the summary window looks while your mouse is away from it. At 0% it vanishes, and reappears when you hover where it sits.",

        dropSection        = "When a wishlist item drops",
        dropSound          = "Play a sound on a drop",
        dropSoundDesc      = "A sound plays when a tracked item drops, a bigger one when you looted it yourself. The on-screen alert shows either way.",
        raidRollAlert      = "Alert on a raid group roll",
        raidRollAlertDesc  = "A banner across the top of the screen when a tracked item goes up for a group roll. Raid groups only.",

        bonusRollSection   = "Bonus rolls",
        bonusRollRemind    = "Remind me after an eligible run",
        bonusRollRemindDesc = "A popup after a Mythic+ 10 or a Heroic or Mythic raid boss, listing the wishlist items you flagged for a bonus roll there. Only when you hold enough Nebulous Voidcore.",
        bonusRollSound     = "Play a sound with the reminder",
        bonusRollSoundDesc = "A raid warning sound plays alongside the bonus roll popup.",

        specSection        = "Spec reminders",
        specDelay          = "Delay after a boss kill",
        specDelayDesc      = "A spec reminder warns you when something you track on an upcoming boss needs a different loot spec. This is how long after a kill the check runs.",

        clickLeft          = "Left-click",
        clickLeftDesc      = "Which windows a plain left-click on the minimap button toggles. Click again to close them.",
        clickLeftNote      = "An empty wishlist stays shut, so \"Wishlist and Loot Browser\" opens the browser alone until you track something.",
        clickCtrl          = "Ctrl-click",
        clickCtrlDesc      = "Which windows a left-click with Ctrl held toggles.",
        clickShift         = "Shift-click",
        clickShiftDesc     = "Which windows a left-click with Shift held toggles.",
        otherClicks        = "Other clicks",
        clickRight         = "Right-click",
        clickRightValue    = "Settings",
        clickMiddle        = "Middle-click",
        clickMiddleValue   = "Toggle debug mode",
        clickDrag          = "Drag",
        clickDragValue     = "Move the button",

        resetMessages      = "Reset both messages",
        messagesHint       = "When someone else loots an item you track, the alert offers a Whisper and a Party button. These are what they send. %item% becomes the item link, %looter% the person who looted it. A box saves when you click away from it.",
        whisperEditor      = "Whisper to the looter",
        partyEditor        = "Message to your group",
        exampleItem        = "[Example Item]",
        exampleLooter      = "Teammate",
        examplePreview     = "Whisper: %s\nParty: %s",
    },

    slash = {
        addUsage         = "usage: /wishlist add <itemID or item link>",
        addUsagePrefixed = "Loot Wishlist: usage /wishlist add <itemID or item link>",
        noItemWithID     = "no item found with ID %s.",
        addedToWishlist  = "added %s to your wishlist.",
        uiNotLoadedItem  = "Loot Wishlist: UI module not loaded. Item tracked.",
        uiNotLoaded      = "Loot Wishlist: UI module not loaded.",
        browserNotLoaded = "Loot Wishlist: browser module not loaded.",
        remindersNotLoaded = "Loot Wishlist: reminders module not loaded.",
        vaultNotLoaded   = "Loot Wishlist: vault module not loaded.",
        shareNotLoaded   = "Loot Wishlist: share module not loaded.",
        alertsNotReady   = "Loot Wishlist: alerts module not ready.",
        removed          = "Loot Wishlist: removed",
        notTracked       = "Loot Wishlist: item not tracked; usage /wishlist remove <itemID>",
        tracking         = "Loot Wishlist: tracking",
        itemsSuffix      = "item(s)",
        openOptions      = "Open Interface Options and look for 'Loot Wishlist'.",
        specReset        = "Loot Wishlist: spec reminder reset. Target a boss or re-enter to trigger again.",
        clearedAll       = "Loot Wishlist: cleared all tracked items",
        usage            = "/wishlist commands: show | hide | browse | settings | add <ID> | remove <ID> | list | clear | export | import | debug | reset-spec | raidinfo",
    },
})
