-- Loot Wishlist: User-facing strings.
-- Centralised here so wording can be tweaked without hunting through feature
-- files. Format strings use Lua's standard %s / %d placeholders; pass through
-- string.format at the call site.
--
-- Debug and dev-command output stays inline with the code that emits it, being
-- diagnostics rather than copy. So do Const.DIFFICULTY_NAMES: Const.DiffTag
-- matches on their wording to work out a difficulty tag, so they are keys as
-- much as labels and cannot be reworded freely.

LootWishlist = LootWishlist or {}

LootWishlist.Strings = LuckyStrings.New("LootWishlist.Strings", {
    addon = {
        title  = "Lucky's Loot Wishlist",
        short  = "Loot Wishlist",
        prefix = "|cffC9A84CLoot Wishlist|r: ",
        loaded = "Loot Wishlist loaded. Track loot from the Adventure Guide! Use /wishlist for help.",
    },

    minimap = {
        tooltipTitle = "|cffffd100Lucky's Loot Wishlist|r",
        leftClick    = "Left-click: %s",
        ctrlClick    = "Ctrl-click: %s",
        shiftClick   = "Shift-click: %s",
        rightClick   = "Right-click: Open settings",
        middleClick  = "Middle-click: Toggle dev mode",
        drag         = "Drag: Move button",
        actionBoth     = "Wishlist and Loot Browser",
        actionWishlist = "Wishlist only",
        actionBrowser  = "Loot Browser only",
    },

    templates = {
        defaultWhisper = "Hey %looter%. If %item% is tradeable and you don't need it, could I roll on it? Been after that one.",
        defaultParty   = "If %item% can be traded and isn't an upgrade for you, I'd really appreciate it.",
    },

    alerts = {
        dropped            = "Wishlist item dropped:",
        lowerTrack         = "Same item, on a lower track than the %s copy on your wishlist.",
        lowerTrackUnnamed  = "Same item, on a lower track than the copy on your wishlist.",
        rollNow            = "Roll now if needed!",
        unknownItem        = "[unknown]",
        fallbackItem       = "[item]",
        whisper            = "Whisper",
        party              = "Party",
        dismiss            = "Dismiss",
        looterLowerIlvl    = "%s is wearing item level %d in that slot. Likely an upgrade for them, so it may not be tradeable.",
        looterEmptySlot    = "%s has nothing in that slot. Likely an upgrade for them, so it may not be tradeable.",
        fallbackWhisper    = "Hi %s, grats! If %s is tradeable, could I please have it? It's on my wishlist.",
        fallbackParty      = "If %s is tradeable, I'd love it (wishlist). Thanks!",
        whisperCommand     = "/w %s %s",
    },

    wishlist = {
        title              = "Loot Wishlist",
        unknownBoss        = "Unknown Boss",
        manuallyAdded      = "Manually Added",
        anySpec            = "|cff8a7e6a{any spec}|r",
        raidTag            = "  |cffff8000[Raid]|r",
        instanceHeading    = "|cffffd100%s|r  (%d)%s",
        bossHeading        = "   |cffc9a84c%s|r  (%d)",
        noItems            = "No items",
        oneItem            = "1 item",
        manyItems          = "%d items",
        clearAll           = "Clear All",
        clearAllConfirm    = "This will remove ALL wishlist items for this character. Are you sure?",
        export             = "Export",
        import             = "Import",
        paste              = "Paste List",
        browseLoot         = "Browse Loot",
        removeFromWishlist = "Remove from wishlist",
        markObtained       = "Mark as obtained",
        markObtainedLine   = "Keeps the item on the list but stops its alerts and reminders.",
        notObtained        = "Not obtained after all",
        notObtainedLine    = "Puts the item back on the list and starts its alerts again.",
        bonusRollTitle     = "Mark as bonus roll target",
        bonusRollLine1     = "Reminds you to spend a Nebulous Voidcore charge",
        bonusRollLine2     = "after a M+ 10+ run or Heroic/Mythic raid boss kill.",
        searchPlaceholder  = "Search items, bosses, instances...",
        noMatches          = "No matches.",
        filters            = "Filters",
        noFilters          = "Showing everything",
        filterSlot         = "Slot",
        allSlots           = "All Slots",
        otherSlot          = "Other",
        resetFilters       = "Reset Filters",
        order              = "Order",
        orderTip           = "Click to change how bosses are ordered",
        orderJournal       = "Journal order",
        orderCount         = "Most items first",
    },

    browser = {
        title             = "Loot Browser",
        trackVeteran      = "Heroic dungeons, Raid Finder raids",
        trackChampion     = "Mythic dungeons, Normal raids",
        trackHero         = "Mythic+ dungeons from +%d, Heroic raids",
        trackMyth         = "Mythic+ vault from +%d, Mythic raids",
        journalNotReady   = "Journal data is not available yet. Try again in a moment.",
        waitingForJournal = "Waiting for the Adventure Guide to close...",
        loading           = "Loading...",
        unknownBoss       = "Unknown Boss",
        noItems           = "No items.",
        noMatches         = "No matches.",
        status            = "|cffe8dcc8%d|r item%s shown%s|cffe8dcc8%d|r on wishlist",
        classLoot         = " loot",
        viewOnly          = "view only, switch back to your class to add",
        noTrackTable      = "journal has no %s table, showing %s",
        entireSeason      = "Entire Season",
        allDungeons       = "All Dungeons",
        allRaids          = "All Raids",
        addToWishlist     = "Add to wishlist",
        removeFromWishlist = "Remove from wishlist",
        veryRare          = "Very Rare",
        bySlot            = "By Slot",
        bySource          = "By Source",
        allSlots          = "All Slots",
        filters           = "Filters",
        filterClass       = "Class and Spec",
        filterSlot        = "Slot",
        filterStats       = "Stats",
        statsAny          = "Any of these stats",
        statsAll          = "All of these stats",
        statsOnly         = "Only these stats",
        statsTipAny       = "Any of %s",
        statsTipAll       = "All of %s",
        statsTipOnly      = "Only %s",
        noFilters         = "Showing everything",
        resetFilters      = "Reset Filters",
        groupToSlot       = "Click to group by slot",
        groupToSource     = "Click to group by source",
        searchPlaceholder = "Search items, bosses, slots...",
        statCrit          = "Crit",
        statHaste         = "Haste",
        statMastery       = "Mast",
        statVersatility   = "Vers",
    },

    bonusRollBlock = {
        passed     = "Bonus Roll passed. %s",
        locked     = "Bonus Roll locked. %s Click the dice to unlock it.",
        passedPlain = "Bonus Roll passed.",
        lockedPlain = "Bonus Roll locked. Click the dice to unlock it.",
        content    = "You do not keep the popup in %s.",
        keyLevel   = "This key is below your minimum of %d.",
        notFlaggedBoss    = "Nothing you track on this boss is flagged for a bonus roll.",
        notFlaggedDungeon = "Nothing you track in this dungeon is flagged for a bonus roll.",
        lockTitle  = "Bonus Roll Locked",
        lockHint   = "Click to unlock the roll.",
        contexts   = {
            mythicplus = "Mythic+",
            raidLFR    = "Raid Finder",
            raidNormal = "Normal raids",
            raidHeroic = "Heroic raids",
            raidMythic = "Mythic raids",
            delve      = "Delves",
            dungeon    = "Dungeons",
            hunts      = "Hunts",
        },
    },

    bonusRoll = {
        reminderTitle = "Bonus Roll Reminder",
        charges       = "Charges: %d  (cost %d per roll)",
        available     = "Bonus Roll Available",
        spendOne      = "Spend a charge in |cffffd100%s|r:",
        spendMany     = "Spend %d charges on |cffffd100%s|r:",
        thisDungeon   = "this dungeon",
        thisBoss      = "this boss",
        noneFlagged   = "(no items flagged for bonus roll)",
        testTitle     = "Bonus Roll Reminder (Test)",
        testSubtitle  = "Test popup",
    },

    bonusRollOdds = {
        wanted        = "|cffe8dcc8%d%%|r chance of a wishlist item from %s\n(%d of the %d that can drop for you)",
        nothingWanted = "None of the %d items that can drop for you from %s are on your wishlist",
        emptyTable    = "No loot table for your class here",
        spent         = "Charges spent here: |cffe8dcc8%d|r",
        betterSpec    = "Loot spec |cffffd100%s|r would be |cffffd100%d%%|r (%d of %d)",
        reading       = "Reading this boss's loot table...",
        notInInstance = "odds need a dungeon or raid. Enter one and try again.",
        reportHeader  = "Bonus roll odds in %s:",
    },

    tokenOdds = {
        title      = "Tier Token Odds",
        alone      = "No one else wears %s in your %d player group.",
        oneOther   = "1 other %s wearer in your %d player group.",
        manyOthers = "%d other %s wearers in your %d player group.",
        yourOdds   = "Your odds",
        fairOdds   = "A fair split",
        pctWhole   = "%d%%",
        pctTenth   = "%.1f%%",
        worse      = "|cffe06c6cWorse than a fair split for a group this size.|r",
        better     = "|cff69db7cBetter than a fair split for a group this size.|r",
        even       = "Exactly a fair split for a group this size.",
        notInRaid  = "tier token odds need a raid group. Join one and try again.",
        noToken    = "Your class takes no tier token.",
    },

    share = {
        exportTitle       = "Export Wishlist",
        importTitle       = "Import Wishlist",
        notAnExport       = "that string is not a Loot Wishlist export.",
        newerVersion      = "that string was made by a newer version of Loot Wishlist. Please update the addon.",
        noItems           = "that string contains no wishlist items.",
        tooManyItems      = "that string holds more than %d items and cannot be imported.",
        oneItem           = "1 item",
        manyItems         = "%d items",
        imported          = "imported %s, replacing your old wishlist.",
        allAlreadyTracked = "every item in the import was already on your wishlist.",
        addedOneExisting  = "added %s to your wishlist. 1 item from the import was already tracked.",
        addedManyExisting = "added %s to your wishlist. %d items from the import were already tracked.",
        added             = "added %s to your wishlist.",
        nothingToExport   = "your wishlist is empty, nothing to export.",
        importPrompt      = "Import %s: add to this character's wishlist, or replace it?",
        importAdd         = "Add",
        importReplace     = "Replace",
        importCancel      = "Cancel",
        tooManyPopups     = "could not ask how to import, too many popups are on screen. Close them and import again.",
    },

    gearImport = {
        title             = "Paste a Gear List",
        hint              = "Paste a best-in-slot table copied from Wowhead or Icy Veins, or any item links. Items are matched against this season's dungeon and raid loot at the Loot Browser's current track. If a paste does not work, join the Discord from the settings panel and share what you tried.",
        importButton      = "Import",
        close             = "Close",
        nothingPasted     = "Nothing to import. Paste a list first.",
        readingTables     = "Reading this season's drop tables...",
        waitingForJournal = "Waiting for the Adventure Guide to close...",
        tablesTimedOut    = "Could not read the drop tables. Open the Loot Browser once, then try again.",
        noMatches         = "Nothing on that list matches this season's dungeon or raid loot.",
        tooMany           = "That list holds more than %d items and cannot be imported.",
        added             = "added %s from the pasted list.",
        addedExisting     = "added %s from the pasted list. %d already tracked.",
        allExisting       = "every item on the pasted list was already on your wishlist.",
    },

    journal = {
        trackItem      = "Track this item",
        noItemID       = "Loot Wishlist: Could not find item ID for this item",
        bonusRollTitle = "Mark as bonus roll target",
        bonusRollLine1 = "Reminds you to spend a Nebulous Voidcore charge",
        bonusRollLine2 = "after running this dungeon (M+ 10+) or killing",
        bonusRollLine3 = "this raid boss (Heroic / Mythic).",
    },

    vault = {
        title             = "Loot Wishlist",
        matchesLine       = "This reward matches an item on your wishlist:",
        lowerTrack        = "Below the %s track on your wishlist.",
        lowerTrackUnnamed = "Below the track on your wishlist.",
    },

    tooltips = {
        onWishlist = "On your wishlist:",
    },

    planner = {
        appropriateSpec  = "appropriate spec",
        askGroup         = "Ask group to help with wishlist items:",
        askGroupLine     = "- %s (%s): %s",
    },

    reminders = {
        upcomingTitle  = "Loot still to come",
        markedOne      = "The marked item needs %s",
        markedMany     = "The marked items need %s",
        rollOdds       = "Bonus roll %d%%",
        rollOddsSpec   = "Bonus roll %d%%, |cffffd100%d%% as %s|r",
        moreItems      = "+%d more",
        switchToSpec   = "Switch to %s",
        needsSpec      = "Needs loot spec: %s",
        assistWhisper  = "Hey %s, could you set your loot spec to %s for %s? It's on my wishlist.",
        assistParty    = "%s, could you set loot spec to %s for %s?",
        whisperCommand = "/w %s %s",
    },

    settings = {
        debugMode          = "Debug mode",
        debugModeDesc      = "Prints what the addon is doing to chat. Useful when reporting a problem.",
        minimapButton      = "Minimap button",
        minimapButtonDesc  = "Show the Loot Wishlist button on the minimap. The Minimap group sets what each click opens.",

        whatsNew           = "What's New",
        versionInfo        = "Version info",
        utilsLabel         = "Lucky's Utils",

        groupWishlist      = "Wishlist",
        groupSummary       = "Summary",
        groupBonusRolls    = "Bonus Rolls",
        groupMinimap       = "Minimap",
        groupMessages      = "Messages",

        wishlistBehaviour  = "Wishlist behaviour",
        raidSection        = "In a raid",

        trackHigher        = "Also track higher difficulties",
        trackHigherDesc    = "Adding a dungeon item on Normal also tracks it on Heroic, Mythic and Mythic+. Turn this off to track only the difficulty you picked.",
        hideObtained       = "Hide obtained items",
        hideObtainedDesc   = "Items you tick as obtained stay in the wishlist window, greyed out under their boss. Ticking this takes them off the screen instead. Either way they raise no alerts or reminders.",
        vaultStar          = "Star wishlist items in the Great Vault",
        vaultStarDesc      = "Puts a pulsing star on any Great Vault reward you track. A silver star means the reward is a lower track than the copy you track. Hover the star to see which wishlist entries it matches.",
        tooltipStatus      = "Wishlist status on item tooltips",
        tooltipStatusDesc  = "Any item on your wishlist says so on its tooltip, naming the boss it drops from and the difficulties you track it at. Bags, vendors, chat links, the Adventure Guide and the Great Vault included.",

        raidTokenOdds      = "Show tier token odds in a raid",
        raidTokenOddsDesc  = "Tier tokens are split by armour type, so every token of yours is shared between everyone in the group wearing it. Joining a raid, or anyone joining yours, opens a window counting the others in your armour and what that leaves your odds at, against the odds a fair split of a group that size would give. Turning this off leaves /wishlist tokens to open it.",
        raidTokenOddsDifficulties     = "Difficulties",
        raidTokenOddsDifficultiesDesc = "Limit which raid difficulties open the window. Whatever you leave unticked, /wishlist tokens still opens it there.",
        raidTokenOddsNote  = "Still being built, so it will keep changing. Say what you want from it on the Discord: https://discord.gg/ptTtYyAjdZ",

        hideSummary        = "Hide the summary window",
        hideSummaryDesc    = "The summary window is the small note listing what you track, grouped by dungeon and boss. Ticking this keeps it off the screen without changing your wishlist.",
        hideSummaryCombat  = "Hide the summary in combat and Mythic+",
        hideSummaryCombatDesc = "The summary window disappears while you are in combat or inside a Mythic+ run, then comes back when you leave.",
        summaryOrder       = "Order bosses by",
        summaryOrderDesc   = "Journal order lists bosses the way the raid runs. Most items first puts the boss you track the most items on at the top, and does the same for dungeons and raids. The wishlist window follows the same order.",
        summaryOpacity     = "Summary opacity when not hovered",
        summaryOpacityDesc = "How solid the summary window looks while your mouse is away from it. At 0% it vanishes, and reappears when you hover where it sits.",

        dropSection        = "When a wishlist item drops",
        dropSound          = "Play a sound on a drop",
        dropSoundDesc      = "A sound plays when a tracked item drops, a bigger one when you looted it yourself. The on-screen alert shows either way.",
        raidRollAlert      = "Alert on a raid group roll",
        raidRollAlertDesc  = "A banner across the top of the screen when a tracked item goes up for a group roll. Raid groups only.",

        bonusRollSection   = "Bonus rolls",
        bonusRollRemind    = "Remind me after an eligible run",
        bonusRollRemindDesc = "A popup after a Mythic+ 10 or a Heroic or Mythic raid boss, listing the wishlist items you flagged for a bonus roll there. Only when you hold enough Nebulous Voidcore.",
        bonusRollSound     = "Play a sound with the reminder",
        bonusRollSoundDesc = "A raid warning sound plays alongside the bonus roll popup.",
        bonusRollOdds      = "Show what a charge is worth",
        bonusRollOddsDesc  = "A line under the Bonus Roll popup giving your chance of a wishlist item, counted against the loot that can drop for you, plus what you have already spent there and whether another loot spec would do better.",

        blockDismiss       = "Prevent accidental bonus rolls",
        blockDismissDesc   = "Automatically passes on the Bonus Roll popup that appears at the end of content, except in the situations selected below.",
        blockDismissNote   = "This is a per-character setting.",
        blockAction        = "When a popup is not wanted",
        blockActionDesc    = "Locking keeps the popup on screen with the roll greyed out and says why, so a setting you have not got right yet can never cost you a roll. Click the dice to unlock it and roll anyway.",
        blockActionLock    = "Lock the roll and warn me",
        blockActionPass    = "Pass it automatically",
        blockActionWarn    = "Passing cannot be undone. Every popup passed is a bonus roll you never make, so anything that boss might have given you is missed for that kill.",
        blockOnlyFlagged        = "Only keep for flagged bosses",
        blockOnlyFlaggedDesc    = "Narrows everything below to bosses you flagged a wishlist item on, using the bonus roll button on a wishlist row. A boss with nothing flagged is passed even where its content is kept.",
        blockKeepMythicPlus     = "Keep in Mythic+",
        blockKeepMythicPlusDesc = "Show the Bonus Roll popup after Mythic+ runs.",
        blockMinKeyLevel        = "Minimum key level",
        blockMinKeyLevelDesc    = "Only keep the popup on keys at or above this level. Keys below this level are always dismissed.",
        blockKeepRaids          = "Keep in Raids",
        blockKeepRaidsDesc      = "Show the Bonus Roll popup after raid bosses.",
        blockRaidDifficulties   = "Difficulties",
        blockRaidDifficultiesDesc = "Limit which raid difficulties keep the popup.",
        blockRaidLFR            = "Raid Finder",
        blockRaidNormal         = "Normal",
        blockRaidHeroic         = "Heroic",
        blockRaidMythic         = "Mythic",
        blockKeepDelve          = "Keep in Delves",
        blockKeepDelveDesc      = "Show the Bonus Roll popup after delve completions.",
        blockKeepDungeon        = "Keep in Dungeons",
        blockKeepDungeonDesc    = "Show the Bonus Roll popup after Normal, Heroic, and Mythic-0 dungeon runs.",
        blockKeepHunts          = "Keep in Hunts",
        blockKeepHuntsDesc      = "Show the Bonus Roll popup after completing hunts.",

        specSection        = "Spec reminders",
        specDelay          = "Delay after a boss kill",
        specDelayDesc      = "A spec reminder warns you when something you track on an upcoming boss needs a different loot spec. This is how long after a kill the check runs.",

        clickLeft          = "Left-click",
        clickLeftDesc      = "Which windows a plain left-click on the minimap button toggles. Click again to close them.",
        clickLeftNote      = "An empty wishlist stays shut, so \"Wishlist and Loot Browser\" opens the browser alone until you track something.",
        clickCtrl          = "Ctrl-click",
        clickCtrlDesc      = "Which windows a left-click with Ctrl held toggles.",
        clickShift         = "Shift-click",
        clickShiftDesc     = "Which windows a left-click with Shift held toggles.",
        otherClicks        = "Other clicks",
        clickRight         = "Right-click",
        clickRightValue    = "Settings",
        clickMiddle        = "Middle-click",
        clickMiddleValue   = "Toggle debug mode",
        clickDrag          = "Drag",
        clickDragValue     = "Move the button",

        resetMessages      = "Reset both messages",
        messagesHint       = "When someone else loots an item you track, the alert offers a Whisper and a Party button. These are what they send. %item% becomes the item link, %looter% the person who looted it. A box saves when you click away from it.",
        whisperEditor      = "Whisper to the looter",
        partyEditor        = "Message to your group",
        exampleItem        = "[Example Item]",
        exampleLooter      = "Teammate",
        examplePreview     = "Whisper: %s\nParty: %s",
    },

    slash = {
        addUsage         = "usage: /wishlist add <itemID or item link>",
        addUsagePrefixed = "Loot Wishlist: usage /wishlist add <itemID or item link>",
        noItemWithID     = "no item found with ID %s.",
        addedToWishlist  = "added %s to your wishlist.",
        uiNotLoadedItem  = "Loot Wishlist: UI module not loaded. Item tracked.",
        uiNotLoaded      = "Loot Wishlist: UI module not loaded.",
        browserNotLoaded = "Loot Wishlist: browser module not loaded.",
        remindersNotLoaded = "Loot Wishlist: reminders module not loaded.",
        vaultNotLoaded   = "Loot Wishlist: vault module not loaded.",
        shareNotLoaded   = "Loot Wishlist: share module not loaded.",
        alertsNotReady   = "Loot Wishlist: alerts module not ready.",
        removed          = "Loot Wishlist: removed",
        notTracked       = "Loot Wishlist: item not tracked; usage /wishlist remove <itemID>",
        tracking         = "Loot Wishlist: tracking",
        itemsSuffix      = "item(s)",
        openOptions      = "Open Interface Options and look for 'Loot Wishlist'.",
        specReset        = "Loot Wishlist: spec reminder reset. Target a boss or re-enter to trigger again.",
        clearedAll       = "Loot Wishlist: cleared all tracked items",
        usage            = "/wishlist commands: show | hide | browse | odds | tokens | settings | add <ID> | remove <ID> | list | clear | export | import | paste | debug | reset-spec | raidinfo",
    },
})
